version: "3.8"

services:
  auth:
    build:
      context: ../FantasyF1-Auth
    container_name: auth-service
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"
    env_file: .env
    networks:
      - backend

  business-logic:
    build:
      context: ../FantasyF1
    container_name: logic-service
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file: .env
    networks:
      - backend

  dbapi:
    build:
      context: ../FantasyF1-DBAPI
    container_name: dbapi-service
    ports:
      - "${DBAPI_PORT}:${DBAPI_PORT}"
    env_file: .env
    networks:
      - backend
      - db-net

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
    networks:
      - db-net

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
    networks:
      - db-net

volumes:
  mongo-data:

networks:
  backend:
  db-net:
