name: Deploy to Swarm

on:
  push:
    branches: [main]
  workflow_dispatch:   # ← permite rulare manuală
  repository_dispatch:
    types: [swarm-deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying..."
